# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20160606_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='firstName',
            field=models.CharField(default='ray', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='lastName',
            field=models.CharField(default='mar', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='referal',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
